config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, :controllers => { registrations: 'registrations' }
  root "posts#index"
  resources :posts do
    resources :comments
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  extend ActsAsTree::TreeWalker
  validates :content, presence: true
  belongs_to :author
  belongs_to :post
  acts_as_tree order: 'created_at'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, :post_date, presence: true
  belongs_to :author
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authenticate_author!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author_id = params[:author_id]
    if @comment.save
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  private

  def comment_params
    params.permit(:content, :author_id, :post_id, :parent_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @author = Author.find(params[:post][:author_id])
    @post = @author.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path
    else
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :author_id, :post_date)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:author).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:author).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/authors/shared/_links.html.erb
<div class="col-center col-md-6">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end -%>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end -%>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end -%>
  <% end -%>
</div>

app/views/comments/show.html.erb
<%= @comment.content %>

<%= link_to "Edit", edit_post_comment_path(@post, @comment) %> |
<%= link_to(post_comment_path(@post, @comment),
  data: {
    confirm: 'You sure?',
    method: 'delete'
  }
) do %>
  Delete
<% end %>
<%= form_tag(controller: "comments", action: "create", method: "post") do %>
  <%= hidden_field_tag :author_id, current_author.id %>
  <%= hidden_field_tag :post_id, @post.id %>
  <%= hidden_field_tag :parent_id, @comment.id %>
  <%= text_area_tag :content %>
  <%= submit_tag "reply" %>
<% end %>

<% @comment.children.each do |comment| %>
  "<%= comment.content %>"<br>
  <i>posted at: <%= comment.created_at %></i><br>
  <i>Author:</i> <%= comment.author.name %><br>
  <%= link_to 'Reply', post_comment_path(@post, comment) %><br><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HnClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", posts_path, class: "nav navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if author_signed_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'Sign Out', destroy_author_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_author_session_path, method: :get %></li>
          <li><%= link_to 'Sign Up', new_author_registration_path, method: :get %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-center">
    <%= form_for @post do |f| %>
      <%= f.hidden_field :post_date, :value => Date.today %>
      <%= f.hidden_field :author_id, :value => current_author.id %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_field :content, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-block btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="col-md-8 col-center post-tile">
  <h3><%= link_to post.title, post_path(post) %></h3>
  <i>posted: <%= post.post_date %></i>
  <br>
  <i>author: <%= post.author.name %></i>
  <div class="comments-count">
    <%= link_to post.comments.length.to_s + " comments", post_path(post) %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render partial: "form" %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <% @posts.each do |post| %>
      <%= render partial: 'post', locals: {post: post} %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.title %>
<br>
<i>posted at: <%= @post.post_date %></i>
<br><br>
<%= @post.content %>
<br>
<%= link_to "Edit", edit_post_path(@post) %> |
<%= link_to(post_path(@post),
  data: {
    confirm: 'You sure?',
    method: 'delete'
  }
) do %>
  Delete
<% end %>
<%= form_tag(post_comments_path(@post), method: "post") do %>
  <%= hidden_field_tag :author_id, current_author.id %>
  <%= text_field_tag :content %>
  <%= submit_tag "Add a Comment" %>
<% end %>
<% @post.comments.each do |comment| %>
  <% if comment.parent == nil %>
    <div class="comment">
      "<%= comment.content %>"<br>
      <i>posted at: <%= comment.created_at %></i><br>
      <i>Author:</i> <%= comment.author.name %><br>
      <%= link_to 'Reply', post_comment_path(@post, comment) %><br><br>
    </div>
    <% comment.walk_tree do |comment, level| %>
      <% @margin= "margin-left:"+(level * 40).to_s+"px;" %>
      <% @class="color"+(((level+1) % 6 == 0 ? 1 : level + 1)).to_s %>
      <div style=<%= @margin %>>
        <div class="comment">
          <div class=<%= @class %>>
            "<%= comment.content %>"<br>
            <i>posted at: <%= comment.created_at %></i><br>
            <i>Author:</i> <%= comment.author.name %><br>
            <%= link_to 'Reply', post_comment_path(@post, comment) %><br><br>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>